name: Build and Trigger

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build documentation
        uses: JetBrains/writerside-github-action@v4
        with:
          instance: All
          artifact: webHelpALL2-all.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs-artifact
          path: artifacts/webHelpALL2-all.zip

  trigger:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Trigger target repository
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: cau-dream-team/cau-dream-team-website
          event-type: update_notes
          client-payload: '{"artifact_name": "docs-artifact"}'
